// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTGWWs1Yx_-14yOPD7VWSaVvz56pIuNi0',
    appId: '1:897794454926:web:ee24dc990544887988a0df',
    messagingSenderId: '897794454926',
    projectId: 'chatapp-f05aa',
    authDomain: 'chatapp-f05aa.firebaseapp.com',
    storageBucket: 'chatapp-f05aa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmr-aLZJR5Ch0i9LnTu5yqNDwipGU1hqc',
    appId: '1:897794454926:android:ee43f7bac5fd99ad88a0df',
    messagingSenderId: '897794454926',
    projectId: 'chatapp-f05aa',
    storageBucket: 'chatapp-f05aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrG0mWU7evZ0YR0CU-S5m9mLXgV4pNJsc',
    appId: '1:897794454926:ios:5bbed06e6f3dea0e88a0df',
    messagingSenderId: '897794454926',
    projectId: 'chatapp-f05aa',
    storageBucket: 'chatapp-f05aa.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrG0mWU7evZ0YR0CU-S5m9mLXgV4pNJsc',
    appId: '1:897794454926:ios:5bbed06e6f3dea0e88a0df',
    messagingSenderId: '897794454926',
    projectId: 'chatapp-f05aa',
    storageBucket: 'chatapp-f05aa.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTGWWs1Yx_-14yOPD7VWSaVvz56pIuNi0',
    appId: '1:897794454926:web:3e606db7020e341588a0df',
    messagingSenderId: '897794454926',
    projectId: 'chatapp-f05aa',
    authDomain: 'chatapp-f05aa.firebaseapp.com',
    storageBucket: 'chatapp-f05aa.appspot.com',
  );
}
